- hosts: localhost
  connection: local
  remote_user: root
  vars:
    htcondor_version: 25.x
    htcondor_keyring_path: /etc/apt/keyrings/htcondor.asc
    htcondor_repo_list_path: /etc/apt/sources.list.d/htcondor.list
    htcondor_role_submit: true
    htcondor_password: changeme
    htcondor_domain: '{{ galaxy_user_name }}'
    htcondor_server: localhost
    htcondor_firewall_condor: false
    htcondor_firewall_nfs: false

  pre_tasks:
    # This pre-task addresses the systemd service that is installed by the role, 
    # which cannot function inside the container. 
    # Therefore, we use an sysvinit script to manage HTCondor during the playbook execution.
    # The init script will be removed later in the post-tasks, as we will use 
    # supervisor to manage HTCondor.
    - name: Create HTCondor init script
      copy:
        dest: /etc/init.d/condor
        mode: '0755'
        content: |
          #!/bin/sh
          HTCONDOR_DIR="/usr/sbin"
          case "$1" in
              start)
                  echo "Starting HTCondor..."
                  $HTCONDOR_DIR/condor_master
                  ;;
              stop)
                  echo "Stopping HTCondor..."
                  killall -r '.*condor.*'
                  ;;
              restart)
                  echo "Restarting HTCondor..."
                  $0 stop
                  $0 start
                  ;;
          esac
          exit 0

    - name: Register HTCondor init script
      command: update-rc.d condor defaults

  tasks:
    - name: Install HTCondor repository prerequisites
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present
        update_cache: true

    - name: Ensure APT keyring directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add HTCondor signing key
      get_url:
        url: "https://htcss-downloads.chtc.wisc.edu/repo/keys/HTCondor-{{ htcondor_version }}-Key"
        dest: "{{ htcondor_keyring_path }}"
        mode: "0644"

    - name: Configure HTCondor apt repository
      copy:
        dest: "{{ htcondor_repo_list_path }}"
        content: |
          # HTCondor repository for the {{ htcondor_version }} feature versions
          deb [signed-by={{ htcondor_keyring_path }}] https://htcss-downloads.chtc.wisc.edu/repo/ubuntu/{{ htcondor_version }} {{ ansible_distribution_release }} main
          deb-src [signed-by={{ htcondor_keyring_path }}] https://htcss-downloads.chtc.wisc.edu/repo/ubuntu/{{ htcondor_version }} {{ ansible_distribution_release }} main

    - name: Install HTCondor
      apt:
        name: condor
        state: present
        update_cache: true

    - name: Create log files for HTCondor
      file:
        path: "/var/log/condor/{{ item }}"
        state: touch
        owner: condor
      loop:
        - StartLog
        - StarterLog
        - CollectorLog
        - NegotiatorLog

    - name: Configure HTCondor
      lineinfile:
        path: /etc/condor/condor_config.local
        create: yes
        line: "{{ item }}"
      loop:
        - 'DISCARD_SESSION_KEYRING_ON_STARTUP=False'
        - 'TRUST_UID_DOMAIN=true'

  # Remove the init script and systemd
  post_tasks:
    - name: Stop HTCondor service
      command: /etc/init.d/condor stop

    - name: Remove HTCondor init script
      file:
        path: /etc/init.d/condor
        state: absent

    - name: Remove HTCondor init script registration
      command: update-rc.d -f condor remove
    
    - name: Purge systemd and perform cleanup
      shell: apt purge -y systemd && apt-get autoremove -y && apt-get clean
