---
roles:
  - name: galaxyproject.postgresql
    version: 1.1.8
  - name: geerlingguy.docker
    version: 7.9.0
  - name: usegalaxy_eu.flower
    version: 2.1.1
  - name: grycap.htcondor
    src: https://github.com/usegalaxy-eu/ansible-htcondor-grycap
    version: fe15ce1569e93a9d1030350c42d1af79e8c3e905
  - name: galaxyproject.proftpd
    version: 0.3.3
  - name: geerlingguy.rabbitmq
    src: https://github.com/geerlingguy/ansible-role-rabbitmq
    version: 3.0.0
  - name: geerlingguy.redis
    version: 1.9.1
  - name: galaxyproject.repos
    version: 0.0.3
  - name: galaxyproject.slurm
    version: 1.0.5
  - name: galaxyproject.tusd
    src: https://github.com/galaxyproject/ansible-role-tusd
    version: e009b498a7989d8002c6a5d104176295d63e9fae
  - name: galaxyproject.nginx
    version: 1.0.0
  - name: usegalaxy_eu.certbot
    version: 0.1.13
  - name: galaxyproject.self_signed_certs
    version: 0.0.4
