---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    cvmfs_role: client
    galaxy_cvmfs_repos_enabled: true
    cvmfs_http_proxies:
      - DIRECT
    cvmfs_cache_base: /var/lib/cvmfs
    cvmfs_quota_limit: 4000
    cvmfs_packages:
      client:
        - cvmfs
        - autofs
  roles:
    - role: galaxyproject.cvmfs
